export const STARTED_BUTTON_CLICK = 'STARTED_BUTTON_CLICK';
export const FETCH_FRIENDS = 'FETCH_FRIENDS';

export const FRIENDS_GET_ALL = 'FRIENDS_GET_ALL';
export const FRIENDS_GET_ALL_SUCCESS = 'FRIENDS_GET_ALL_SUCCESS';
export const FRIENDS_GET_ALL_ERROR = 'FRIENDS_GET_ALL_ERROR';
